title: 青红椒
url: "https://qinghingjiao.com"
# baseurl: "/"

markdown: kramdown
ins_logo: "/bits-logo.png"

tracking_id: UA-69243

footer: yes
footer_url: "https://github.com/ankitsultana/ankitsultana.github.io"
footer_text: "This is a custom-built theme for Jekyll. Please report any issues on GitHub."

favicon: true
favicon_location: "images/favicon.png"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "Home"
    link: "/"
  - name: "Blog"
    link: "/blog"
  - name: "Post"
    link: "/post"
  - name: "Show"
    link: "/show"
  - name: "Projects"
    link: "/projects"
  - name: "About"
    link: "/about"
# 翻页 路径 
  
paginate: 6

permalink: /:title.html
